version: '2'
services:
  omnicore:
    image: tigerseye/docker-omnicore:latest
    ports:
      - "18332:18332"
    volumes:
      - ./data:/data/usdt
    command: "/data/omnicore/bin/omnicored -printtoconsole -datadir=/data/usdt -txindex -testnet"
