version: '2'
services:
#About node_modules.
#By default I override local node_modules directory.
#This is intended for working without installing dependencies by using development images.
  
#Bitcore Full Node
  omnicore:
    ports:
      - "18332:18332"
    volumes:
      - /data:/data/bitcoreroot
    #for prod network > command: bitcore create mynode
    command: "/data/omnicore/bin/omnicored -datadir=/data/bitcoreroot -testnet"
